#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docker" / "nginx" / "generated-backends.conf"
GITMODULES = ROOT / ".gitmodules"


def load_allowed_manifest_roots() -> set[Path]:
    allowed = {
        ROOT / "host" / "net",
        ROOT / "core",
        ROOT / "net",
        ROOT / "team",
    }
    if not GITMODULES.exists():
        return allowed

    for raw_line in GITMODULES.read_text().splitlines():
        line = raw_line.strip()
        if not line.startswith("path = "):
            continue
        submodule_path = line.split("=", 1)[1].strip()
        if submodule_path:
            allowed.add(ROOT / submodule_path)
    return allowed


def parse_manifest(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip()
    required = {"path", "backend", "port"}
    missing = required.difference(data)
    if missing:
        missing_list = ", ".join(sorted(missing))
        raise ValueError(f"{path}: missing {missing_list}")
    return data


def normalize_location_path(value: str) -> str:
    cleaned = value.strip() or "/"
    if not cleaned.startswith("/"):
        cleaned = "/" + cleaned
    if cleaned != "/" and not cleaned.endswith("/"):
        cleaned += "/"
    return cleaned


def build_location_block(repo_name: str, data: dict[str, str]) -> str:
    location_path = normalize_location_path(data["path"])
    backend_host = data["backend"].strip()
    backend_port = data["port"].strip()
    upstream = f"http://{backend_host}:{backend_port}"
    return f"""# {repo_name}
location {location_path} {{
    proxy_pass {upstream};
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}}
"""


def main() -> None:
    manifests: list[tuple[str, dict[str, str]]] = []
    allowed_roots = load_allowed_manifest_roots()

    rg_result = subprocess.run(
        ["rg", "--files", "--hidden", "--no-ignore", "-g", ".backend"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    manifest_paths = [
        ROOT / line.strip()
        for line in rg_result.stdout.splitlines()
        if line.strip()
    ]

    for manifest_path in sorted(manifest_paths, key=lambda item: str(item).lower()):
        relative_parent = manifest_path.parent.relative_to(ROOT)
        if any(part.startswith(".") and part != ".backend" for part in relative_parent.parts):
            continue
        if not any(manifest_path.parent == root or root in manifest_path.parent.parents for root in allowed_roots):
            continue
        manifests.append((relative_parent.as_posix() or ".", parse_manifest(manifest_path)))

    manifests.sort(key=lambda item: len(normalize_location_path(item[1]["path"])), reverse=True)

    blocks = [
        "# Generated by docker/nginx/generate-nginx-conf.py",
        "# Regenerate with: python3 docker/nginx/generate-nginx-conf.py",
        "",
    ]
    blocks.extend(build_location_block(name, data) for name, data in manifests)

    OUTPUT.write_text("\n".join(blocks).rstrip() + "\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} from {len(manifests)} manifest(s).")


if __name__ == "__main__":
    main()
